spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  redis:
    port: 6379
    host: localhost
  datasource:
    url: jdbc:mysql://localhost:3306/token
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: kang0525@
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
auth:
  jwt:
    secret: refreshTokenStudy
