spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  redis:
    port: ${PORT}
    host: ${HOST}
  datasource:
    url: ${DBURL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${PASSWORD}
    username: ${NAME}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
auth:
  jwt:
    header: ${HEADER}
    secret: ${SECRET}
    exp:
      access: ${ACCESS}
      refresh: ${REFRESH}

